---
- name: Enable required leaf NX-OS features
  cisco.nxos.nxos_feature:
    feature: "{{ item }}"
    state: enabled
  loop: "{{ standards.features.leaf.required }}"
  when: "'leaves' in group_names"
