---
- name: Configure L2 overlay VLANs
  ansible.builtin.import_tasks: vlans.yml

- name: Configure L2 VLAN to VNI mappings
  ansible.builtin.import_tasks: vni_mappings.yml

- name: Configure L2 NVE
  ansible.builtin.import_tasks: nve.yml

- name: Configure EVPN L2VNIs
  ansible.builtin.import_tasks: evpn.yml
