---
- name: Configure L2 VLAN to VNI mappings
  cisco.nxos.nxos_vlans:
    config:
      - vlan_id: "{{ item | int }}"
        mapped_vni: "{{ fabric.overlay.vlans[item].vni | int }}"
    state: merged
  loop: "{{ devices[inventory_hostname].overlay.vlans }}"
  when:
    - item | int != fabric.overlay.l3_vni.vlan | int
  loop_control:
    label: "VLAN {{ item }} -> VNI {{ fabric.overlay.vlans[item].vni }}"
