---
all:
  children:
    fabric:
      children:
        spines:
          hosts:
            S-1:
              ansible_host: "<SPINE_MANAGEMENT_IP>"

        leaves:
          hosts:
            L-1:
              ansible_host: "<LEAF1_MANAGEMENT_IP>"

            L-2:
              ansible_host: "<LEAF2_MANAGEMENT_IP>"

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.nxos.nxos
    ansible_user: "<CML_USERNAME>"
    ansible_password: "<CML_PASSWORD>"
