---
- name: Configure loopback IP addresses
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ item.key }}"
        ipv4:
          - address: "{{ item.value.address }}"
  loop: "{{ devices[inventory_hostname].loopbacks | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Configure fabric interfaces as Layer 3
  cisco.nxos.nxos_config:
    parents:
      - "interface {{ item.local_interface }}"
    lines:
      - no switchport
  loop: "{{ topology.fabric_links }}"
  when: item.local_device == inventory_hostname
  loop_control:
    label: "{{ item.local_interface }}"

- name: Configure fabric interfaces as point-to-point
  cisco.nxos.nxos_config:
    parents:
      - "interface {{ item.local_interface }}"
    lines:
      - medium p2p
  loop: "{{ topology.fabric_links }}"
  when: item.local_device == inventory_hostname
  loop_control:
    label: "{{ item.local_interface }}"

- name: Configure fabric interface descriptions and enable interfaces
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ item.local_interface }}"
        description: "{{ item.description }}"
        enabled: true
  loop: "{{ topology.fabric_links }}"
  when: item.local_device == inventory_hostname
  loop_control:
    label: "{{ item.local_interface }}"

- name: Configure fabric interface MTU
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ item.local_interface }}"
        mtu: "{{ fabric.underlay.mtu }}"
  loop: "{{ topology.fabric_links }}"
  when: item.local_device == inventory_hostname
  loop_control:
    label: "{{ item.local_interface }}"

- name: Configure IP unnumbered on fabric interfaces
  cisco.nxos.nxos_config:
    parents:
      - "interface {{ item.local_interface }}"
    lines:
      - "ip unnumbered loopback0"
  loop: "{{ topology.fabric_links }}"
  when: item.local_device == inventory_hostname
  loop_control:
    label: "{{ item.local_interface }}"
