---
- name: Enable PIM sparse mode on loopback interfaces
  cisco.nxos.nxos_config:
    parents:
      - "interface {{ item.key }}"
    lines:
      - ip pim sparse-mode
  loop: "{{ devices[inventory_hostname].loopbacks | dict2items }}"
  when: item.value.pim | default(false) | bool
  loop_control:
    label: "{{ item.key }}"

- name: Enable PIM sparse mode on fabric interfaces
  cisco.nxos.nxos_config:
    parents:
      - "interface {{ item.local_interface if item.local_device == inventory_hostname else item.remote_interface }}"
    lines:
      - ip pim sparse-mode
  loop: "{{ topology.fabric_links }}"
  when:
    - inventory_hostname == item.local_device or inventory_hostname == item.remote_device
  loop_control:
    label: >-
      {{ item.local_interface if item.local_device == inventory_hostname
         else item.remote_interface }}

- name: Configure multicast RP on all fabric switches
  cisco.nxos.nxos_config:
    lines:
      - "ip pim rp-address {{ fabric.multicast.rp.address }} group-list {{ fabric.multicast.rp.group_list }} bidir"
