---
- name: Deploy VXLAN EVPN underlay
  hosts: fabric
  gather_facts: false

  vars_files:
    - ../data/standards.yml
    - ../data/fabric.yml
    - ../data/devices.yml
    - ../data/topology.yml

  roles:
    - role: 01_underlay