---
- name: Deploy VXLAN EVPN overlay
  hosts: leaves
  gather_facts: false

  vars_files:
    - ../data/standards.yml
    - ../data/fabric.yml
    - ../data/devices.yml
    - ../data/topology.yml

  roles:
    - role: 02_overlay_l2
