---
- name: Deploy VXLAN EVPN underlay
  hosts: fabric
  gather_facts: false

  vars_files:
    - ../data/standards.yml
    - ../data/fabric.yml
    - ../data/devices.yml
    - ../data/topology.yml

  roles:
    - role: 01_underlay

  post_tasks:
    - name: Save running configuration to startup configuration
      cisco.nxos.nxos_command:
        commands:
          - copy running-config startup-config
      changed_when: false
