name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    name: Validate Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Ansible dependencies
        run: |
          python -m pip install --upgrade pip

          if [ -s requirements.txt ]; then
            pip install -r requirements.txt
          fi

          if [ -s requirements.yml ]; then
            ansible-galaxy collection install -r requirements.yml
          fi

      - name: Run Ansible Lint
        run: ansible-lint

      - name: Check Section 0 syntax
        run: |
          ansible-playbook --syntax-check playbooks/deploy_features.yml
          ansible-playbook --syntax-check tests/validation/validate_features.yml

      - name: Check Section 1 syntax
        run: |
          ansible-playbook --syntax-check playbooks/deploy_underlay.yml
          ansible-playbook --syntax-check tests/validation/validate_underlay.yml

      - name: Check Section 2 syntax
        run: |
          ansible-playbook --syntax-check playbooks/deploy_overlay_l2.yml
          ansible-playbook --syntax-check tests/validation/validate_overlay_l2.yaml

      - name: Check Section 3 syntax
        run: |
          ansible-playbook --syntax-check playbooks/deploy_overlay_l3.yml
          ansible-playbook --syntax-check tests/validation/validate_overlay_l3.yml

      - name: Check Section 6 syntax
        run: |
          ansible-playbook --syntax-check playbooks/deploy_endpoints.yml
          ansible-playbook --syntax-check tests/validation/validate_endpoints.yml
